apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
spec:
  clusterIP: None  # <-- This makes it headless!
  selector:
    app: mongodb
  ports:
    - port: 27017
      name: mongo
      targetPort: 27017
