apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polybot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bene1310/PolybotInfra.git
    targetRevision: main
    path: k8s/polybot
  destination:
    server: https://kubernetes.default.svc
    namespace: polybot
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
