apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5
  namespace: yolo5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
      labels:
        app: yolo5
    spec:
      containers:
        - name: yolo5
          image: bene1310/yolo5:latest
          imagePullPolicy: Always
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: yolo5-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: yolo5-secrets
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: 80
